/*
 * Automatically generated by Magic
 */
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FlexLayoutModule } from '@angular/flex-layout';

import { MaterialModule } from '@app/material.module';
import { LoaderComponent } from './loader/loader.component';
import { DateSincePipe } from '@app/pipes/date-since.pipe';
import { SafeHtmlPipe } from '@app/pipes/safe-html.pipe';

@NgModule({
  imports: [
    FlexLayoutModule,
    MaterialModule,
    CommonModule,
  ],
  declarations: [
    LoaderComponent,
    DateSincePipe,
    SafeHtmlPipe,
  ],
  exports: [LoaderComponent, DateSincePipe, SafeHtmlPipe],
})
export class SharedModule {}
