/*
 * Automatically generated by Magic
 */
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { marker } from '@biesbjerg/ngx-translate-extract-marker';

import { HomeComponent } from './home.component';
import { Shell } from '@app/shell/shell.service';
import { UserManagementComponent } from '@app/common/user-management/user-management.component';

// Then importing all CRUD components.
import { Aista_crm_accountsComponent } from '../components/aista_crm/accounts/aista_crm_accounts.component';
import { Aista_crm_activitiesComponent } from '../components/aista_crm/activities/aista_crm_activities.component';
import { Aista_crm_activity_typesComponent } from '../components/aista_crm/activity_types/aista_crm_activity_types.component';
import { Aista_crm_contactsComponent } from '../components/aista_crm/contacts/aista_crm_contacts.component';
import { Aista_crm_notificationsComponent } from '../components/aista_crm/notifications/aista_crm_notifications.component';
import { Aista_crm_statusComponent } from '../components/aista_crm/status/aista_crm_status.component';
import { Aista_crm_tasksComponent } from '../components/aista_crm/tasks/aista_crm_tasks.component';


const routes: Routes = [
  Shell.childRoutes([
    { path: '', component: HomeComponent, data: { title: marker('Home') } },
    { path: 'users', component: UserManagementComponent, data: { title: marker('User management') } },

    // Then routes for all CRUD components.
    { path: 'crud/aista_crm/accounts', component: Aista_crm_accountsComponent, data: { title: marker('aista_crm/accounts') } },
    { path: 'crud/aista_crm/activities', component: Aista_crm_activitiesComponent, data: { title: marker('aista_crm/activities') } },
    { path: 'crud/aista_crm/activity_types', component: Aista_crm_activity_typesComponent, data: { title: marker('aista_crm/activity_types') } },
    { path: 'crud/aista_crm/contacts', component: Aista_crm_contactsComponent, data: { title: marker('aista_crm/contacts') } },
    { path: 'crud/aista_crm/notifications', component: Aista_crm_notificationsComponent, data: { title: marker('aista_crm/notifications') } },
    { path: 'crud/aista_crm/status', component: Aista_crm_statusComponent, data: { title: marker('aista_crm/status') } },
    { path: 'crud/aista_crm/tasks', component: Aista_crm_tasksComponent, data: { title: marker('aista_crm/tasks') } },

  ]),
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
  providers: [],
})
export class HomeRoutingModule {}
